In [1]:
import pandas as pd

# importing data
data = pd.read_csv('/content/data_clean.csv')
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50

In [2]:
#selecting the specific columns
selected_data = data[['Name', 'Location', 'Year','Price']]
selected_data.head()

                               Name    Location  Year  Price
0  Hyundai Creta 1.6 CRDi SX Option        Pune  2015  12.50
1                      Honda Jazz V     Chennai  2011   4.50
2                 Maruti Ertiga VDI     Chennai  2012   6.00
3   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013  17.74
4            Nissan Micra Diesel XV      Jaipur  2013   3.50

In [5]:
#Filtering dataset with location and Owner_Type
filtered_data = data[(data["Location"] == "Pune") & (data["Owner_Type"] == "First")]
filtered_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50
6,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,4.78 Lakh,5.20
36,38,Mercedes-Benz M-Class ML 350 CDI,Pune,2013,85000,Diesel,Automatic,First,11.74 kmpl,2987 CC,254.8 bhp,5.0,4.78 Lakh,28.00
66,68,Maruti Ertiga SHVS VDI,Pune,2016,63000,Diesel,Manual,First,24.52 kmpl,1248 CC,88.5 bhp,7.0,4.78 Lakh,8.15
77,81,Tata Zest Revotron 1.2T XE,Pune,2017,70000,Petrol,Manual,First,17.57 kmpl,1193 CC,88.7 bhp,5.0,6.67 Lakh,4.50

In [22]:
#Renaming columns Location, Mileage, Engine, Power with Place, Mileage in kmpl, Engine in CC, Power in bhp
renamed_columns = data.rename(columns={"Location": "Place","Mileage": "Mileage in kmpl", "Engine": "Engine in CC", "Power": "Power in bhp"})
renamed_columns.head()

,Unnamed: 0,Name,Place,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage in kmpl,Engine in CC,Power in bhp,Seats,New_Price,Price,Age,Kilometers_Per_Year
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50,9,4555.555556
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,13,3538.461538
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00,12,7250.000000
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74,11,3697.272727
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50,11,7909.000000

In [23]:
# Mutate operation
# Adding new column "Kilometers_Per_Year"
current_year = 2024
data['Age'] = current_year - data['Year']
data['Kilometers_Per_Year'] = data['Kilometers_Driven'] / data['Age']
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age,Kilometers_Per_Year
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,4.78 Lakh,12.50,9,4555.555556
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,13,3538.461538
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,4.78 Lakh,6.00,12,7250.000000
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,4.78 Lakh,17.74,11,3697.272727
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,4.78 Lakh,3.50,11,7909.000000

In [24]:
# Arranging data based on Car Year
arranged_data = data.sort_values(by="Year")
arranged_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Age,Kilometers_Per_Year
5558,5716,Maruti Zen LX,Jaipur,1998,95150,Petrol,Manual,Third,17.3 kmpl,993 CC,60 bhp,5.0,4.78 Lakh,0.53,26,3659.615385
3039,3138,Maruti Zen LXI,Jaipur,1998,95150,Petrol,Manual,Third,17.3 kmpl,993 CC,60 bhp,5.0,4.78 Lakh,0.45,26,3659.615385
3630,3749,Mercedes-Benz E-Class 250 D W 210,Mumbai,1998,55300,Diesel,Automatic,First,10.0 kmpl,1796 CC,157.7 bhp,5.0,4.78 Lakh,3.90,26,2126.923077
1791,1845,Honda City 1.3 EXI,Pune,1999,140000,Petrol,Manual,First,13.0 kmpl,1343 CC,90 bhp,5.0,4.78 Lakh,0.90,25,5600.000000
1185,1224,Maruti Zen VX,Jaipur,1999,70000,Petrol,Manual,Second,17.3 kmpl,993 CC,60 bhp,5.0,4.78 Lakh,0.77,25,2800.000000

In [25]:
# Group By operation
# Sum of Kilometers_Driven and Mean price for each year in each location
summary_data = data.groupby(["Year", "Location"]).agg({"Kilometers_Driven": "sum","Price": "mean"})
summary_data.head(20)

                Kilometers_Driven  Price
Year Location
1998 Jaipur                190300   0.49
     Mumbai                 55300   3.90
1999 Jaipur                 70000   0.77
     Pune                  140000   0.90
2000 Hyderabad             158000   1.50
     Jaipur                 90000   0.70
     Kolkata               124000   1.95
     Pune                   78000   0.55
2001 Chennai               244000   0.85
     Jaipur                200000   0.70
     Pune                  255943   1.10
2002 Ahmedabad              85000   1.20
     Bangalore             116000   2.75
     Chennai               267811   0.99
     Hyderabad              99000   1.90
     Jaipur                128500   0.57
     Kolkata                69000   1.60
     Mumbai                 60000   0.55
     Pune                   93000   1.00
2003 Chennai               531200   2.50